version: '3.7'
services:
  nestjs-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: production

    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PROD_DB_USER}
      - POSTGRES_PASSWORD=${PROD_DB_PASSWORD}
      - POSTGRES_DB=${PROD_DB_NAME}
    ports:
      - ${PROD_DB_PORT}:${PROD_DB_PORT}